# Generated by Django 3.2.9 on 2021-12-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('long_description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='media')),
                ('slug', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='information',
            name='email',
            field=models.EmailField(max_length=250),
        ),
    ]
